---
engines:
  fixme:
    enabled: true
  govet:
    enabled: true
  golint:
    enabled: true
    checks:
      GoLint/Comments/DocComments:
        enabled: false
      GoLint/Naming/MixedCaps:
        enabled: false

ratings:
  paths:
    - "**.go"

exclude_paths:
  - test/
